import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

interface Segment {
    title?: string;
    narration?: string;
    visual?: string;
    check?: { question?: string; answer?: string };
    edited?: boolean;
}

interface Question {
    id: number;
    question: string;
    options: { text: string; misconception?: string }[];
    correctIndex: number;
    explanation: string;
    level: string;
}

export default function Show({
    version,
    questions,
    levels,
    stats,
}: {
    version: {
        id: number;
        topic: string | null;
        subject: string | null;
        summary: string | null;
        objectives: string[];
        language: string | null;
        languageName: string | null;
        isEnglish: boolean;
        ttsSupported: boolean;
        status: string;
        notes: string | null;
        segments: Segment[];
        lessonNotes: string | null;
        flashcards: { front: string; back: string }[];
        provider: string | null;
        model: string | null;
        generatedAt: string | null;
    };
    questions: Record<string, Question[]>;
    levels: Record<string, string>;
    stats: { segments: number; segmentsEdited: number; questions: number };
}) {
    const [editingSegment, setEditingSegment] = useState<number | null>(null);
    const [editingQuestion, setEditingQuestion] = useState<number | null>(null);
    const [decision, setDecision] = useState<'publish' | 'reject' | null>(null);

    const segmentForm = useForm({ title: '', narration: '', visual: '' });
    const questionForm = useForm<{
        question: string;
        options: { text: string; misconception?: string }[];
        correct_index: number;
        explanation: string;
        level: string;
    }>({ question: '', options: [], correct_index: 0, explanation: '', level: 'basic' });
    const publishForm = useForm({ notes: '' });
    const rejectForm = useForm({ reason: '' });

    return (
        <AuthenticatedLayout header={<h2 className="text-xl font-semibold text-slate-800">Review lesson</h2>}>
            <Head title={`Review: ${version.topic}`} />

            <div className="mx-auto max-w-3xl space-y-5 px-4 py-8 sm:px-6">
                <Link href={route('review.index')} className="text-sm text-slate-500 hover:text-slate-800">
                    ← Review queue
                </Link>

                <section className="rounded-xl border border-slate-200 bg-white p-6">
                    <h1 className="text-lg font-semibold text-slate-900">{version.topic}</h1>
                    <p className="mt-0.5 text-sm text-slate-500">
                        {version.subject} · {version.language}
                        {!version.ttsSupported && !version.isEnglish && (
                            <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-[11px]">
                                text only — no speech voice yet
                            </span>
                        )}
                    </p>
                    {version.summary && <p className="mt-3 text-sm text-slate-700">{version.summary}</p>}

                    <p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">
                        Generated by {version.provider} ({version.model}) on {version.generatedAt}. Nothing here
                        has been seen by a student. {stats.segmentsEdited} of {stats.segments} segments edited
                        so far.
                    </p>

                    {!version.isEnglish && (
                        <p className="mt-2 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">
                            Check that technical terms, formulas and units are still in English with the{' '}
                            {version.languageName} word alongside. Learners write the final exam in English.
                        </p>
                    )}
                </section>

                <section className="space-y-3">
                    <h2 className="font-semibold text-slate-900">Lesson segments</h2>

                    {version.segments.map((segment, index) => (
                        <article key={index} className="rounded-xl border border-slate-200 bg-white p-5">
                            {editingSegment === index ? (
                                <form
                                    onSubmit={(e) => {
                                        e.preventDefault();
                                        segmentForm.put(route('review.segments.update', [version.id, index]), {
                                            preserveScroll: true,
                                            onSuccess: () => setEditingSegment(null),
                                        });
                                    }}
                                    className="space-y-3"
                                >
                                    <input
                                        value={segmentForm.data.title}
                                        onChange={(e) => segmentForm.setData('title', e.target.value)}
                                        className="block w-full rounded-lg border-slate-300 text-sm font-medium"
                                    />
                                    <textarea
                                        rows={4}
                                        value={segmentForm.data.narration}
                                        onChange={(e) => segmentForm.setData('narration', e.target.value)}
                                        className="block w-full rounded-lg border-slate-300 text-sm"
                                        placeholder="What the student hears"
                                    />
                                    <textarea
                                        rows={2}
                                        value={segmentForm.data.visual}
                                        onChange={(e) => segmentForm.setData('visual', e.target.value)}
                                        className="block w-full rounded-lg border-slate-300 text-sm"
                                        placeholder="What builds on screen alongside it"
                                    />
                                    <div className="flex gap-2">
                                        <button className="rounded-lg bg-indigo-600 px-4 py-2 text-xs font-semibold text-white">
                                            Save
                                        </button>
                                        <button
                                            type="button"
                                            onClick={() => setEditingSegment(null)}
                                            className="rounded-lg border border-slate-300 px-4 py-2 text-xs text-slate-600"
                                        >
                                            Cancel
                                        </button>
                                    </div>
                                </form>
                            ) : (
                                <>
                                    <div className="flex items-start justify-between gap-3">
                                        <div className="min-w-0 flex-1">
                                            <p className="font-medium text-slate-900">
                                                {index + 1}. {segment.title}
                                                {segment.edited && (
                                                    <span className="ml-2 rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-normal text-emerald-800">
                                                        edited
                                                    </span>
                                                )}
                                            </p>
                                            <p className="mt-2 whitespace-pre-line text-sm text-slate-700">
                                                {segment.narration}
                                            </p>
                                            {segment.visual && (
                                                <p className="mt-2 rounded bg-slate-50 p-2 text-xs text-slate-600">
                                                    On screen: {segment.visual}
                                                </p>
                                            )}
                                            {segment.check?.question && (
                                                <p className="mt-2 text-xs text-indigo-700">
                                                    Pause and think: {segment.check.question} →{' '}
                                                    {segment.check.answer}
                                                </p>
                                            )}
                                        </div>

                                        <div className="flex shrink-0 flex-col gap-1 text-xs">
                                            <button
                                                onClick={() => {
                                                    setEditingSegment(index);
                                                    segmentForm.setData({
                                                        title: segment.title ?? '',
                                                        narration: segment.narration ?? '',
                                                        visual: segment.visual ?? '',
                                                    });
                                                }}
                                                className="font-medium text-indigo-600 hover:text-indigo-500"
                                            >
                                                Edit
                                            </button>
                                            <button
                                                onClick={() =>
                                                    router.delete(
                                                        route('review.segments.remove', [version.id, index]),
                                                        { preserveScroll: true },
                                                    )
                                                }
                                                className="text-slate-400 hover:text-rose-600"
                                            >
                                                Remove
                                            </button>
                                        </div>
                                    </div>
                                </>
                            )}
                        </article>
                    ))}
                </section>

                {version.lessonNotes && (
                    <section className="rounded-xl border border-slate-200 bg-white p-5">
                        <h2 className="font-semibold text-slate-900">Revision notes</h2>
                        <pre className="mt-3 whitespace-pre-wrap font-sans text-sm text-slate-700">
                            {version.lessonNotes}
                        </pre>
                    </section>
                )}

                <section className="space-y-4">
                    <h2 className="font-semibold text-slate-900">Assessment questions</h2>

                    {Object.entries(levels).map(([level, label]) => (
                        <div key={level}>
                            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                                {label} ({questions[level]?.length ?? 0})
                            </p>

                            <ul className="mt-2 space-y-2">
                                {(questions[level] ?? []).map((question) => (
                                    <li key={question.id} className="rounded-xl border border-slate-200 bg-white p-4">
                                        {editingQuestion === question.id ? (
                                            <form
                                                onSubmit={(e) => {
                                                    e.preventDefault();
                                                    questionForm.put(
                                                        route('review.questions.update', question.id),
                                                        {
                                                            preserveScroll: true,
                                                            onSuccess: () => setEditingQuestion(null),
                                                        },
                                                    );
                                                }}
                                                className="space-y-2"
                                            >
                                                <textarea
                                                    rows={2}
                                                    value={questionForm.data.question}
                                                    onChange={(e) =>
                                                        questionForm.setData('question', e.target.value)
                                                    }
                                                    className="block w-full rounded-lg border-slate-300 text-sm"
                                                />

                                                {questionForm.data.options.map((option, optionIndex) => (
                                                    <div key={optionIndex} className="flex items-center gap-2">
                                                        <input
                                                            type="radio"
                                                            checked={questionForm.data.correct_index === optionIndex}
                                                            onChange={() =>
                                                                questionForm.setData('correct_index', optionIndex)
                                                            }
                                                        />
                                                        <input
                                                            value={option.text}
                                                            onChange={(e) => {
                                                                const options = [...questionForm.data.options];
                                                                options[optionIndex] = {
                                                                    ...options[optionIndex],
                                                                    text: e.target.value,
                                                                };
                                                                questionForm.setData('options', options);
                                                            }}
                                                            className="flex-1 rounded-lg border-slate-300 text-xs"
                                                        />
                                                        <input
                                                            value={option.misconception ?? ''}
                                                            onChange={(e) => {
                                                                const options = [...questionForm.data.options];
                                                                options[optionIndex] = {
                                                                    ...options[optionIndex],
                                                                    misconception: e.target.value,
                                                                };
                                                                questionForm.setData('options', options);
                                                            }}
                                                            placeholder="Mistake this represents"
                                                            className="flex-1 rounded-lg border-slate-300 text-xs"
                                                        />
                                                    </div>
                                                ))}

                                                <textarea
                                                    rows={2}
                                                    value={questionForm.data.explanation}
                                                    onChange={(e) =>
                                                        questionForm.setData('explanation', e.target.value)
                                                    }
                                                    placeholder="Explanation shown after answering"
                                                    className="block w-full rounded-lg border-slate-300 text-xs"
                                                />

                                                <button className="rounded-lg bg-indigo-600 px-4 py-1.5 text-xs font-semibold text-white">
                                                    Save question
                                                </button>
                                            </form>
                                        ) : (
                                            <>
                                                <p className="text-sm font-medium text-slate-900">
                                                    {question.question}
                                                </p>
                                                <ul className="mt-2 space-y-1">
                                                    {question.options.map((option, optionIndex) => (
                                                        <li
                                                            key={optionIndex}
                                                            className={`text-xs ${
                                                                optionIndex === question.correctIndex
                                                                    ? 'font-medium text-emerald-700'
                                                                    : 'text-slate-600'
                                                            }`}
                                                        >
                                                            {optionIndex === question.correctIndex ? '✓' : '·'}{' '}
                                                            {option.text}
                                                            {option.misconception && (
                                                                <span className="ml-2 text-slate-400">
                                                                    ({option.misconception})
                                                                </span>
                                                            )}
                                                        </li>
                                                    ))}
                                                </ul>
                                                <p className="mt-2 text-xs text-slate-500">
                                                    {question.explanation}
                                                </p>

                                                <div className="mt-2 flex gap-3 text-xs">
                                                    <button
                                                        onClick={() => {
                                                            setEditingQuestion(question.id);
                                                            questionForm.setData({
                                                                question: question.question,
                                                                options: question.options,
                                                                correct_index: question.correctIndex,
                                                                explanation: question.explanation,
                                                                level: question.level,
                                                            });
                                                        }}
                                                        className="font-medium text-indigo-600"
                                                    >
                                                        Edit
                                                    </button>
                                                    <button
                                                        onClick={() =>
                                                            router.delete(
                                                                route('review.questions.destroy', question.id),
                                                                { preserveScroll: true },
                                                            )
                                                        }
                                                        className="text-slate-400 hover:text-rose-600"
                                                    >
                                                        Remove
                                                    </button>
                                                </div>
                                            </>
                                        )}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    ))}
                </section>

                <section className="rounded-xl border border-slate-200 bg-white p-6">
                    <h2 className="font-semibold text-slate-900">Your decision</h2>
                    <p className="mt-1 text-sm text-slate-600">
                        Approving puts your name on this lesson. Students will see that you checked it.
                    </p>

                    <div className="mt-4 flex gap-3">
                        <button
                            onClick={() => setDecision(decision === 'publish' ? null : 'publish')}
                            className="rounded-lg bg-emerald-600 px-5 py-2 text-sm font-semibold text-white hover:bg-emerald-500"
                        >
                            Approve and publish
                        </button>
                        <button
                            onClick={() => setDecision(decision === 'reject' ? null : 'reject')}
                            className="rounded-lg border border-slate-300 px-5 py-2 text-sm font-medium text-slate-700"
                        >
                            Send back
                        </button>
                    </div>

                    {decision === 'publish' && (
                        <form
                            onSubmit={(e) => {
                                e.preventDefault();
                                publishForm.post(route('review.publish', version.id));
                            }}
                            className="mt-4 space-y-2"
                        >
                            <input
                                value={publishForm.data.notes}
                                onChange={(e) => publishForm.setData('notes', e.target.value)}
                                placeholder="Any note for the record (optional)"
                                className="block w-full rounded-lg border-slate-300 text-sm"
                            />
                            <button className="rounded-lg bg-emerald-600 px-5 py-2 text-sm font-semibold text-white">
                                Confirm and publish
                            </button>
                        </form>
                    )}

                    {decision === 'reject' && (
                        <form
                            onSubmit={(e) => {
                                e.preventDefault();
                                rejectForm.post(route('review.reject', version.id));
                            }}
                            className="mt-4 space-y-2"
                        >
                            <textarea
                                rows={3}
                                value={rejectForm.data.reason}
                                onChange={(e) => rejectForm.setData('reason', e.target.value)}
                                placeholder="What is wrong? This guides the regeneration."
                                className="block w-full rounded-lg border-slate-300 text-sm"
                            />
                            {rejectForm.errors.reason && (
                                <p className="text-xs text-rose-600">{rejectForm.errors.reason}</p>
                            )}
                            <button className="rounded-lg bg-rose-600 px-5 py-2 text-sm font-semibold text-white">
                                Send back with notes
                            </button>
                        </form>
                    )}
                </section>
            </div>
        </AuthenticatedLayout>
    );
}
